---
docker_pkg_name: docker-ce
docker_version: 17.06.0~ce-0~ubuntu
apt_key_url: https://download.docker.com/linux/ubuntu/gpg
apt_key_sig: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
apt_repository: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable

docker_api_ip: 127.0.0.1
docker_api_port: 2375
docker_storage_driver: overlay2
docker_log_driver: fluentd

docker_mounts:
  docker_dir:
    mount: /var/lib/docker

swarm_port: 2377
swarm_bootstrap_ip: "{{ hostvars[groups['docker-swarm-managers'][0]].ansible_enp0s8.ipv4.address }}"
swarm_listen: "{{ ansible_enp0s8.ipv4.address }}"
swarm_advertise: "{{ ansible_enp0s8.ipv4.address }}"
