---

- name: Check docker version 
  shell: dpkg-query -s "{{ docker_pkg_name }}" | grep -E 'Version:.*$' | sed 's/.*\:\ //g'
  ignore_errors: true
  register: docker_installed_version

- name: 
  set_fact:
    docker_upgrade_done: "{% if docker_installed_version.stdout_lines | join(' ') == docker_upgrade_version %}True{% else %}False{% endif %}"
