---

- name: Check docker version 
  shell: dpkg-query -s "{{ docker_pkg_name }}" | grep -E 'Version:.*$' | sed 's/.*\:\ //g'
  ignore_errors: true
  register: docker_installed_version

- debug:
    var: docker_installed_version

- name: 
  set_fact:
    docker_upgrade_done: False | default(True)|bool
  when: docker_installed_version != docker_upgrade_version

- debug:
    var: docker_upgrade_done 
...
