---

- name: Docker repo configuration
  include_role:
    name: docker
    tasks_from: repo

- name: Ensure daemon.json doesn't exists
  file:
    path: /etc/docker/daemon.json
    state: absent

- name: Install docker package
  apt:
    name: "{{ docker_pkg_name }}={{ docker_version }}"
    update_cache: yes

- name: UpdateDB configuration
  include_role:
    name: docker
    tasks_from: updatedb

- name: Daemon configuration
  include_role:
    name: docker
    tasks_from: daemon

- name: Service configuration
  include_role:
    name: docker
    tasks_from: service

