---

- name: Check if docker installed
  include_role:
    name: docker
    tasks_from: check_install

- name: Install docker
  include_role:
    name: docker
    tasks_from: install
  when: docker_install_needed

- name: Set swarm facts
  include_role:
    name: docker
    tasks_from: node_facts

- name: Intitialize swarm
  include_role:
    name: docker
    tasks_from: swarm
  when: docker_info_facts.Swarm.LocalNodeState == 'inactive'

- name: Set swarm facts
  include_role:              
    name: docker             
    tasks_from: node_facts  

...
