---

- name: Add Docker repository key
  apt_key:
    id: "{{ apt_key_sig }}"
    keyserver: "{{ apt_key_url }}"
    state: present

- name: Clean old Docker repository to avoid mixing channels stable/edge
  file:
    path: /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list
    state: absent

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "{{ apt_repository }}"
    filename: "docker-repo"
    mode: '644'
    update_cache: yes
    state: present

