---

- name: Docker repo configuration
  include_role:
    name: docker
    tasks_from: repo

- name: Drain node
  include_role:
    name: docker
    tasks_from: node_drain

- name: Upgrade docker to "{{ docker_upgrade_version }}"
  apt:
    name: "{{ docker_pkg_name }}={{ docker_upgrade_version }}"
    update_cache: yes

- name: UpdateDB configuration
  include_role:
    name: docker
    tasks_from: updatedb

- name: Daemon configuration
  include_role:
    name: docker                  
    tasks_from: daemon

- name: Service configuration
  include_role:
    name: docker                  
    tasks_from: service

- name: Activate node
  include_role:
    name: docker
    tasks_from: node_activate

- name: Waiting for containers to re-balance after drain
  pause:
    seconds: 30
